### ISSUE TITLE
Variaveis de ambiente Postgres

### ISSUE THREAD

**Issue by mmfalcao** [cod3rcursos/curso-docker#2]
Adicionar variaveis de ambiente para conexão com postgres, no docker-compose.yml
```
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
```
